services:
  orion-redis:
    image: redis:7-alpine
    command: ["redis-server", "--appendonly", "yes", "--maxmemory-policy", "allkeys-lru"]
    ports:
      - "6379:6379"
    volumes:
      - orion_redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG || exit 1"]
      interval: 5s
      timeout: 2s
      retries: 5
    networks:
      - app-net

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=orion:orion-redis:6379:0
    ports:
      - "8085:8085"
    restart: unless-stopped
    depends_on:
      orion-redis:
        condition: service_healthy
    networks:
      - app-net

  redis-exporter:
    image: oliver006/redis_exporter:latest
    environment:
      - REDIS_ADDR=redis://orion-redis:6379
    ports:
      - "9121:9121"
    restart: unless-stopped
    depends_on:
      orion-redis:
        condition: service_healthy
    networks:
      - app-net

networks:
  app-net:
    external: true

volumes:
  orion_redis_data:
