# ───────────────────────────────────────────────────────────────
# 🚌 Orion Bus — Mesh Message Broker (Redis core + metrics)
# Node-aware | Ephemeral | Telemetry-mounted
# ───────────────────────────────────────────────────────────────

services:
  bus-core:
    image: redis:7-alpine
    container_name: ${PROJECT:-orion}-bus-core
    command: ["redis-server", "--appendonly", "yes", "--maxmemory-policy", "allkeys-lru"]
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - ${TELEMETRY_ROOT}/${PROJECT}/bus/data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG || exit 1"]
      interval: 5s
      timeout: 2s
      retries: 5
    networks:
      app-net:
        aliases:
          - bus-core
          - ${PROJECT:-orion}-bus-core

  bus-exporter:
    image: oliver006/redis_exporter:latest
    container_name: ${PROJECT:-orion}-bus-exporter
    environment:
      - REDIS_ADDR=redis://bus-core:6379
    ports:
      - "${REDIS_EXPORTER_PORT:-9121}:9121"
    depends_on:
      bus-core:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - app-net

# ───────────────────────────────────────────────────────────────
# Shared Network
# ───────────────────────────────────────────────────────────────
networks:
  app-net:
    external: true

