# schema/graphdb_schema.ttl
@prefix cj: <http://conjourney.net/schema#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix owl:  <http://www.w3.org/2002/07/owl#> .
@prefix xsd:  <http://www.w3.org/2001/XMLSchema#> .
@prefix rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .

cj:MemoryEvent a owl:Class ;
    rdfs:label "Memory Event" ;
    rdfs:comment "An event or reflection captured by the mesh." .

cj:memory_id a owl:DatatypeProperty ;
    rdfs:domain cj:MemoryEvent ;
    rdfs:range xsd:string ;
    rdfs:label "Memory ID" ;
    rdfs:comment "Globally shared memory ID for alignment across storage tiers." .

cj:thread_id a owl:DatatypeProperty ;
    rdfs:domain cj:MemoryEvent ;
    rdfs:range xsd:string ;
    rdfs:label "Thread ID" ;
    rdfs:comment "An identifier linking related memory entries in a sequence." .

cj:origin a owl:DatatypeProperty ;
    rdfs:domain cj:MemoryEvent ;
    rdfs:range xsd:string ;
    rdfs:label "Origin" ;
    rdfs:comment "The originating subsystem or sensory pathway." .

cj:stimulus a owl:DatatypeProperty ;
    rdfs:domain cj:MemoryEvent ;
    rdfs:range xsd:string ;
    rdfs:label "Stimulus" ;
    rdfs:comment "What external or internal input triggered the memory." .

cj:generatedBy a owl:ObjectProperty ;
    rdfs:domain cj:MemoryEvent ;
    rdfs:range cj:MemoryEvent ;
    rdfs:label "Generated By" ;
    rdfs:comment "Indicates which prior memory generated or inferred this one." .

cj:nextInThread a owl:ObjectProperty ;
    rdfs:domain cj:MemoryEvent ;
    rdfs:range cj:MemoryEvent ;
    rdfs:label "Next in Thread" ;
    rdfs:comment "Links memory events in narrative or causal order." .

