from __future__ import annotations

REPO_DEV_SNAPSHOT_SLOT = "repo_dev_snapshot"
REPO_DEV_SNAPSHOT_TAG = "repo_dev_snapshot"

PR_BODY_MAX_CHARS = 2000
CARD_SUMMARY_MAX_CHARS = 800
JOURNAL_TITLE_MAX_CHARS = 120
JOURNAL_BODY_MAX_CHARS = 4000

DEFAULT_LOOKBACK_DAYS = 1
