from __future__ import annotations

CHAT_DEV_DIGEST_TAG = "chat_dev_digest"
COMPACTOR_KIND = "chat_history_log"
DEFAULT_TIMEZONE = "America/Denver"
DEFAULT_LOOKBACK_HOURS = 24
DEFAULT_MAX_TURNS = 30

CARD_SUMMARY_MAX_CHARS = 1600
JOURNAL_TITLE_MAX_CHARS = 120
JOURNAL_BODY_MAX_CHARS = 4000

# Per-turn trim before digest LLM
DIGEST_TURN_PROMPT_MAX_CHARS = 400
DIGEST_TURN_RESPONSE_MAX_CHARS = 600
