from __future__ import annotations

import importlib
import json
import logging
import os
import sys
from pathlib import Path
from typing import Any, Dict, Optional, List
from unittest.mock import MagicMock

import pytest

from orion.schemas.agents.schemas import FinalAnswer
from orion.schemas.cortex.schemas import ExecutionPlan, PlanExecutionArgs, PlanExecutionRequest
from orion.schemas.cortex.types import StepExecutionResult


META_PLAN_TEXT = "Gather requirements. Create a guide. Review and refine."
FINAL_GUIDE = """\
Discord Deployment Guide (Concrete)

This is the concrete output generated by `finalize_response`, not meta-planning scaffolding.
"""


def _import_service_app(service_root: Path, module_qualified: str):
    old_sys_path = list(sys.path)
    for k in list(sys.modules.keys()):
        if k == "app" or k.startswith("app."):
            sys.modules.pop(k, None)

    sys.path.insert(0, str(service_root))
    try:
        return importlib.import_module(module_qualified)
    finally:
        sys.path = old_sys_path


@pytest.mark.timeout(30)
def test_supervisor_meta_plan_triggers_finalize_response(monkeypatch, caplog):
    """
    Proof-oriented: supervisor must detect a shallow meta-plan in planner output
    (instructional mode) and then re-run `finalize_response`.
    """

    repo_root = Path(__file__).resolve().parents[1]
    cortex_exec_root = repo_root / "services" / "orion-cortex-exec"

    # Important: PlanRunner captures the Supervisor symbol at import time inside app.router.
    # Import only router and take Supervisor from there to ensure monkeypatch applies to the correct class object.
    router_mod = _import_service_app(cortex_exec_root, "app.router")
    Supervisor = router_mod.Supervisor
    PlanRunner = router_mod.PlanRunner

    called_tool_ids: List[str] = []

    # Stub planner: returns final_answer with meta-plan text and no action.
    async def _fake_planner_step(
        self: Supervisor,
        *,
        source,
        goal_text: str,
        toolset: list,
        trace: list,
        ctx: Dict[str, Any],
        correlation_id: str,
        diagnostic: bool = False,
    ):
        planner_step = StepExecutionResult(
            status="success",
            verb_name="planner",
            step_name="planner_react",
            order=-1,
            result={
                "PlannerReactService": {
                    "trace": [{"thought": "shallow meta-plan", "action": None}],
                }
            },
            latency_ms=1,
            node="test",
            logs=["planner ok (stubbed)"],
            error=None,
        )
        return None, planner_step, FinalAnswer(content=META_PLAN_TEXT, structured={}), None

    # Stub action execution so we can assert `finalize_response` invocation without requiring bus/LLM.
    async def _fake_execute_action(
        self: Supervisor,
        *,
        source,
        action: Dict[str, Any],
        ctx: Dict[str, Any],
        correlation_id: str,
        mode: str,
        packs: List[str],
    ):
        tool_id = str((action or {}).get("tool_id") or "")
        called_tool_ids.append(tool_id)
        assert tool_id == "finalize_response"
        return StepExecutionResult(
            status="success",
            verb_name=tool_id,
            step_name=tool_id,
            order=100,
            result={"LLMGatewayService": {"llm_output": FINAL_GUIDE}},
            latency_ms=1,
            node="test",
            logs=["finalize_response ok (stubbed)"],
            error=None,
        )

    monkeypatch.setattr(Supervisor, "_planner_step", _fake_planner_step)
    monkeypatch.setattr(Supervisor, "_execute_action", _fake_execute_action)

    # PlanRunner decides supervised path for depth==2 or agent_runtime.
    req = PlanExecutionRequest(
        plan=ExecutionPlan(
            verb_name="agent_runtime",
            label="agent-runtime",
            description="supervisor meta-plan proof plan",
            category="agentic",
            priority="normal",
            interruptible=True,
            can_interrupt_others=False,
            timeout_ms=10_000,
            max_recursion_depth=1,
            steps=[],
            metadata={"mode": "agent", "execution_depth": "2"},
        ),
        args=PlanExecutionArgs(
            request_id="req-test",
            user_id="u1",
            trigger_source="test",
            extra={"mode": "agent", "recall": {"enabled": False}},
        ),
        context={},
    )

    ctx = {
        "mode": "agent",
        "max_steps": 1,
        "messages": [{"role": "user", "content": "Please provide instructions on how to deploy you onto Discord."}],
        "packs": ["executive_pack", "memory_pack"],
        # Crucial: instructional mode so quality gate decides to rewrite.
        "output_mode": "implementation_guide",
        "response_profile": "technical_delivery",
    }

    caplog.set_level(logging.INFO)
    runner = PlanRunner()
    bus = MagicMock()
    source = MagicMock()
    correlation_id = "corr-supervisor-meta-plan"

    import asyncio

    res = asyncio.run(
        runner.run_plan(
            bus,
            source=source,
            req=req,
            correlation_id=correlation_id,
            ctx=ctx,
        )
    )

    assert res.final_text is not None
    assert "finalize_response" in called_tool_ids

    final_text = res.final_text
    # Must not leak meta-plan scaffolding language.
    assert "gather requirements" not in final_text.lower()
    assert "create a guide" not in final_text.lower()
    assert "review and refine" not in final_text.lower()

    # For proof bundle later: ensure supervisor took a finalize action, not a shallow pass-through.
    assert final_text.strip() == FINAL_GUIDE.strip()

    if os.environ.get("ORION_PROOF_WRITE") == "1":
        repo_root = Path(__file__).resolve().parents[1]
        proof_dir = repo_root / "docs" / "postflight" / "proof"
        proof_dir.mkdir(parents=True, exist_ok=True)
        log_excerpt = "\n".join(
            [
                rec.message
                for rec in caplog.records
                if "supervisor_finalize_response_invoked" in rec.message
                or "quality_evaluator_rewrite" in rec.message
                or "supervisor_wiring" in rec.message
            ][:200]
        )
        evidence = {
            "planner_meta_plan_text_excerpt": META_PLAN_TEXT[:120],
            "output_mode": ctx.get("output_mode"),
            "response_profile": ctx.get("response_profile"),
            "called_tool_ids": called_tool_ids,
            "final_answer_excerpt": final_text[:500],
            "log_excerpt": log_excerpt,
        }
        (proof_dir / "supervisor_meta_plan_finalize_evidence.json").write_text(
            json.dumps(evidence, indent=2, ensure_ascii=False),
            encoding="utf-8",
        )
        (proof_dir / "supervisor_meta_plan_finalize_evidence.md").write_text(
            "\n".join(
                [
                    "# Supervisor Meta-Plan → finalize_response Evidence (Pass 3)",
                    "",
                    "This evidence is produced by a deterministic harness (planner step + finalize action are stubbed; the meta-plan quality gate logic is real).",
                    "",
                    "## Called tool ids",
                    "```",
                    " -> ".join(evidence["called_tool_ids"]),
                    "```",
                    "",
                    "## Log excerpt",
                    "```",
                    evidence["log_excerpt"],
                    "```",
                    "",
                    "## Final answer excerpt",
                    "```text",
                    evidence["final_answer_excerpt"],
                    "```",
                ]
            ),
            encoding="utf-8",
        )

