services:
  coqui-tts-downloader:
    image: ghcr.io/coqui-ai/tts-cpu
    container_name: tts-downloader
    # This entrypoint is the key. It will wait until DNS is working
    # before it tries to run the tts-server (which triggers the download).
    entrypoint: /bin/sh -c "while ! getent hosts coqui.gateway.scarf.sh > /dev/null; do echo 'Waiting for DNS...'; sleep 2; done && tts-server"
    environment:
      # We still need to tell it which model to download
      - TTS_MODEL_NAME=tts_models/en/ljspeech/vits
    # NO volumes are mounted. This ensures it downloads to its own internal storage.
    # NO ports are needed. We just need it to run and download.

