services:
  redis:
    image: redis:7-alpine
    container_name: vision-redis

  vision:
    build: .
    container_name: vision-service
    depends_on:
      - redis
    environment:
      SOURCE: "${REOLINK_URL}"
      WIDTH: "${WIDTH}"
      HEIGHT: "${HEIGHT}"
      FPS: "${FPS}"
      DETECTORS: "${DETECTORS}"
      MOTION_MIN_AREA: "${MOTION_MIN_AREA}"
      STREAM_ID: "${STREAM_ID}"
      REDIS_URL: "redis://redis:6379/0"
      ENABLE_UI: "${ENABLE_UI}"

      # YOLO config
      ENABLE_YOLO: "${ENABLE_YOLO}"
      YOLO_MODEL: "${YOLO_MODEL}"
      YOLO_CLASSES: "${YOLO_CLASSES}"
      YOLO_CONF: "${YOLO_CONF}"
      YOLO_DEVICE: "${YOLO_DEVICE}"
    ports:
      - "8000:8000"
    deploy: {}
    gpus: all
