[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "orionbus"
version = "0.1.0"
description = "Orion Mesh Redis bus client"
authors = [{name = "Orion Project"}]
license = {text = "MIT"}
dependencies = ["redis>=5.0.0"]
