version: "3.9"

services:
  orion-langchain:
    build: .
    container_name: orion-langchain
    ports:
      - "8090:8090"
    environment:
      - ORION_BRAIN_URL=http://orion-brain-service:8088
      - LLM_MODEL=mistral:instruct
      - CHROMA_DIR=/data/chroma
      - EMBED_MODEL=sentence-transformers/all-MiniLM-L6-v2
      - PG_HOST=chrysalis
      - PG_DB=conjourney
      - PG_USER=juniper
      - PG_PASS=${PG_PASS}
      - GRAPHDB_URL=http://graphdb:7200/repositories/orion
    volumes:
      - ./data:/data
    networks:
      - app-net
    depends_on:
      - orion-brain-service

  orion-reflection:
    build: .
    container_name: orion-reflection
    command: ["bash", "-c", "while true; do python reflect.py; sleep 86400; done"]
    environment:
      - ORION_BRAIN_URL=http://orion-brain-service:8088
      - LLM_MODEL=mistral:instruct
      - CHROMA_DIR=/data/chroma
      - EMBED_MODEL=sentence-transformers/all-MiniLM-L6-v2
      - PG_HOST=chrysalis
      - PG_DB=conjourney
      - PG_USER=juniper
      - PG_PASS=${PG_PASS}
      - GRAPHDB_URL=http://graphdb:7200/repositories/orion
    volumes:
      - ./data:/data
    networks:
      - app-net
    depends_on:
      - orion-brain-service
      - orion-langchain

networks:
  app-net:
    external: true
