services:
  orion-sql-client:
    image: dpage/pgadmin4:7
    container_name: orion-sql-client
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: "${PGADMIN_DEFAULT_EMAIL}"
      PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_DEFAULT_PASSWORD}"
    ports:
      - "8083:80"   # Web UI on localhost:8083
    depends_on:
      - orion-sql-db
    networks:
      - app-net

networks:
  app-net:
    external: true
