from orion.schemas.storage_write_projection import (
    STORAGE_WRITE_CHANNEL,
    STORAGE_WRITE_NODE_ID,
    STORAGE_WRITE_SOURCE_SERVICE,
    STORAGE_WRITE_TRACE_PREFIX,
)

STORAGE_WRITE_PROJECTION_ID = "active_storage_write_projection"
STORAGE_WRITE_GRAMMAR_CURSOR_NAME = "storage_write_grammar_reducer"
STORAGE_WRITE_REDUCER_ID = "storage_write_reducer"
STORAGE_WRITE_TARGET_KIND = "storage_write"

__all__ = [
    "STORAGE_WRITE_CHANNEL",
    "STORAGE_WRITE_GRAMMAR_CURSOR_NAME",
    "STORAGE_WRITE_NODE_ID",
    "STORAGE_WRITE_PROJECTION_ID",
    "STORAGE_WRITE_REDUCER_ID",
    "STORAGE_WRITE_SOURCE_SERVICE",
    "STORAGE_WRITE_TARGET_KIND",
    "STORAGE_WRITE_TRACE_PREFIX",
]
