# Configuration for the inference pipeline on new, unseen documents

# --- Model ---
# Path to the saved BERTopic model to load for inference
model_load_path: "/app/models/final_topic_model"

# --- Input Data ---
# Path to the new data that needs topic predictions
data_path: "/app/data/new_unseen_documents.csv"
text_column: "document_text"

# --- Output ---
# Path where the inference results (CSV with topic assignments) will be saved
output_path: "/app/data/inference_results.csv"
