# Configuration for the main model training pipeline

# --- Input Data ---
data_path: "/app/data/sample_documents.csv"
text_column: "document_text"

# --- Output ---
# Path where the trained BERTopic model will be saved INSIDE the container
model_save_path: "/app/models/final_topic_model"

# --- Model Components ---
embedding_model: "all-MiniLM-L6-v2"

vectorizer_params:
  stop_words: "english"
  ngram_range: [1, 2]

# --- KMeans Parameters ---
# The number of clusters (topics) to create.
# This value should be chosen based on the results from the tuning pipeline.
kmeans_params:
  n_clusters: 12 # Example value - CHANGE THIS after running the tuning script
  random_state: 42
