"""The exact edits that turn Bonsai's embedded GGUF chat template into
config/chat_templates/ternary-bonsai-2-27b.jinja. Both hunks are copied verbatim from the
Qwen3.8-27B Q4 (Unsloth) template, so Bonsai accepts the same request shapes Q4 serves:

1. Drop the ``No user query found in messages.`` raise. cortex-exec sends verb steps as a lone
   system message, and that raise made every one of them an HTTP 500.
2. Merge leading system/developer messages into one system block. ``_build_hop_messages`` can send
   ``[system, system]``, for example when ctx carries a self_study system message
   (verb_adapters.py), and Bonsai raised ``System message must be at the beginning.`` on that.

Tool-call XML, thinking blocks and reasoning-effort handling stay Bonsai's own.
"""
from __future__ import annotations

EDITS: list[tuple[str, str]] = [
    (  # 1. the raise
        "{%- if ns.multi_step_tool %}\n"
        "    {{- raise_exception('No user query found in messages.') }}\n"
        "{%- endif %}\n",
        "",
    ),
    (  # 2a. collect leading system/developer messages
        "{%- set reasoning_instructions = '' %}\n",
        "{%- set sysns = namespace(count=0, text='') %}\n"
        "{%- for message in messages %}\n"
        "    {%- if sysns.count == loop.index0 and (message.role == 'system' or message.role == 'developer') %}\n"
        "        {%- set sys_content = render_content(message.content, false, true)|trim %}\n"
        "        {%- if sys_content %}\n"
        "            {%- set sysns.text = sysns.text + ('\\n' if sysns.text else '') + sys_content %}\n"
        "        {%- endif %}\n"
        "        {%- set sysns.count = sysns.count + 1 %}\n"
        "    {%- endif %}\n"
        "{%- endfor %}\n"
        "{%- set num_sys = sysns.count %}\n"
        "{%- set merged_system = sysns.text %}\n"
        "{%- set reasoning_instructions = '' %}\n",
    ),
    (  # 2b. tools branch: emit the merged system text
        "    {%- if messages[0].role == 'system' %}\n"
        "        {%- set content = render_content(messages[0].content, false, true)|trim %}\n"
        "        {%- if content %}\n"
        "            {{- '\\n\\n' + content }}\n"
        "        {%- endif %}\n",
        "    {%- if merged_system %}\n"
        "        {{- '\\n\\n' + merged_system }}\n",
    ),
    (  # 2c. no-tools branch
        "    {%- if messages[0].role == 'system' %}\n"
        "        {%- set content = render_content(messages[0].content, false, true)|trim %}\n"
        "        {%- if content %}\n"
        "            {{- '<|im_start|>system\\n' + (reasoning_instructions + '\\n\\n' if reasoning_instructions else '')  + content + '<|im_end|>\\n' }}\n"
        "        {%- elif reasoning_instructions %}\n"
        "            {{- '<|im_start|>system\\n' + reasoning_instructions + '<|im_end|>\\n' }}\n"
        "        {%- endif %}\n",
        "    {%- if merged_system %}\n"
        "        {{- '<|im_start|>system\\n' + (reasoning_instructions + '\\n\\n' if reasoning_instructions else '')  + merged_system + '<|im_end|>\\n' }}\n",
    ),
    (  # 2d. main loop: skip the merged leading system messages; a later one is still an error
        "{%- for message in messages %}\n"
        "    {%- set content = render_content(message.content, true)|trim %}\n"
        "    {%- if message.role == \"system\" %}\n"
        "        {%- if not loop.first %}\n"
        "            {{- raise_exception('System message must be at the beginning.') }}\n"
        "        {%- endif %}\n",
        "{%- for message in messages %}\n"
        "    {%- if loop.index0 >= num_sys %}\n"
        "    {%- set content = render_content(message.content, true)|trim %}\n"
        "    {%- if message.role == \"system\" or message.role == \"developer\" %}\n"
        "        {{- raise_exception('System message must be at the beginning.') }}\n",
    ),
    (  # 2e. close the skip guard
        "        {{- raise_exception('Unexpected message role.') }}\n"
        "    {%- endif %}\n"
        "{%- endfor %}\n",
        "        {{- raise_exception('Unexpected message role.') }}\n"
        "    {%- endif %}\n"
        "    {%- endif %}\n"
        "{%- endfor %}\n",
    ),
]

TRAILER = (
    "\n{#- Orion: Ternary-Bonsai-2-27B's embedded GGUF template with two hunks copied from the Qwen3.8-27B"
    " Q4 (Unsloth) template: no 'No user query found' raise (system-only requests 500'd), and leading"
    " system/developer messages merged. Generated by services/orion-llamacpp-host/tests/bonsai_template_patch.py;"
    " see docs/superpowers/pr-reports/2026-10-07-bonsai-chat-template-pr.md #}"
)


def build(embedded: str) -> str:
    out = embedded
    for old, new in EDITS:
        if out.count(old) != 1:
            raise ValueError(f"edit anchor not found exactly once: {old[:60]!r}")
        out = out.replace(old, new)
    return out + TRAILER


if __name__ == "__main__":
    import sys
    sys.stdout.write(build(open(sys.argv[1], encoding="utf-8").read()))
