#!/usr/bin/env python3
"""Detect and auto-restore a destructively-modified graphify-out/ working
tree -- the uncommitted counterpart to scripts/check_graph_node_loss.py's
commit-time gate.

Why this exists, and why it is a *worktree* check rather than another commit
gate: the known destructive-update failure mode (`graphify update .` silently
discarding most of the graph -- see CLAUDE.md's graphify section and
scripts/safe_graphify_update.sh) leaves its damage sitting as an UNCOMMITTED
modification. The pre-commit gate (scripts/check_graph_node_loss.py) only
fires at `git commit` time; a session that never commits the damage never
trips it, but every `graphify query`/`explain`/`path` in the meantime is
silently answering from a gutted graph. Confirmed live 2026-08-21: a session
opened onto a working tree at 2,505 nodes / 2.8MB against a committed 28,306
nodes / 44MB -- 91% gone -- with nothing to stop it until a human noticed the
file size.

This module also catches a SECOND, distinct failure mode documented in
safe_graphify_update.sh's own header ("second incident", 2026-08-12): a
restore that only puts back graph.json and leaves its siblings
(manifest.json, GRAPH_REPORT.md) stale. Those three files are always
regenerated together by `graphify update`, so if graph.json matches HEAD but
either sibling does not, that mismatch is itself the defect -- independent of
any node-count math. Confirmed live again 2026-08-21 in this exact repo: a
prior manual restore fixed graph.json (28306 nodes, clean) but left
manifest.json (335 vs 3596 entries) and GRAPH_REPORT.md (4035 lines short)
sitting in the pre-restore, shrunken state -- while GRAPH_REPORT.md is the
file CLAUDE.md tells every agent to read for broad architecture review.

Both cases restore the SAME way: `git checkout HEAD -- <path>`, i.e. put back
whatever is already committed. This is always safe to automate because it can
never lose committed history -- only uncommitted drift in a build artifact
that is regenerated by a tool, not hand-authored. The one real risk is
discarding an in-progress INTENTIONAL re-extraction that has not been
committed yet; two mitigations cover that:

  1. The same escape hatch as the commit gate (ORION_ALLOW_GRAPH_SHRINK=1)
     skips the auto-restore entirely -- set it while a deliberate
     re-extraction is in flight, same as you would before committing one.
  2. Every file this script is about to overwrite is snapshotted first, so
     an intentional-but-unflagged in-progress change is never unrecoverably
     lost -- see BACKUP_ROOT below.

Usage:
    python3 scripts/check_graph_worktree_integrity.py              # detect + auto-restore
    python3 scripts/check_graph_worktree_integrity.py --check-only  # report only, never restore
    python3 scripts/check_graph_worktree_integrity.py --json

Exit codes:
    0 = clean (nothing dirty, or dirty but within threshold, or restored, or
        skipped via the escape hatch -- never blocking; this is a detector,
        not a gate)
    2 = could not run the check (unreadable/unparseable HEAD input, not a git
        repo), OR a destructive/desync case was found but the restore itself
        failed (see stderr -- the backup, if one was taken, is still there)
"""
from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
import sys
import time
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from check_graph_node_loss import (  # noqa: E402
    COUNTED_KEYS,
    DEFAULT_MAX_LOSS_PCT,
    ENV_ESCAPE,
    _counts,
    loss_pct,
)

GRAPH_PATH = "graphify-out/graph.json"
MANIFEST_PATH = "graphify-out/manifest.json"
REPORT_PATH = "graphify-out/GRAPH_REPORT.md"
# Only files git actually tracks belong in this bundle -- graph.html and the
# .graphify_* caches are gitignored (confirmed via `git check-ignore -v`), so
# there is no HEAD baseline to restore them from, and safe_graphify_update.sh
# already covers cleaning those up on the command-wrapped path.
BUNDLE = (GRAPH_PATH, MANIFEST_PATH, REPORT_PATH)

# Own env var, not check_graph_node_loss's GRAPHIFY_COMMIT_MAX_NODE_LOSS_PCT --
# same convention safe_graphify_update.sh already established (its own
# GRAPHIFY_UPDATE_MAX_NODE_LOSS_PCT): each guard point gets an independently
# tunable knob that happens to share the same default, rather than one name
# reused across conceptually different gates (commit-time vs worktree-time).
ENV_THRESHOLD = "GRAPHIFY_WORKTREE_MAX_NODE_LOSS_PCT"

ENV_BACKUP_ROOT = "GRAPHIFY_WORKTREE_GUARD_BACKUP_ROOT"
BACKUP_ROOT = os.environ.get(ENV_BACKUP_ROOT, "/tmp/graphify_worktree_guard_backups")


def resolve_threshold(explicit: float | None) -> float:
    """Same resolution order everywhere this guard is invoked (CLI flag >
    env var > default) so the hook and the CLI can never silently disagree."""
    if explicit is not None:
        return explicit
    raw = os.environ.get(ENV_THRESHOLD, "").strip()
    try:
        return float(raw) if raw else DEFAULT_MAX_LOSS_PCT
    except ValueError:
        return DEFAULT_MAX_LOSS_PCT


def _run(args: list[str]) -> subprocess.CompletedProcess:
    return subprocess.run(args, capture_output=True, text=True, check=False)


def _repo_root() -> str | None:
    proc = _run(["git", "rev-parse", "--show-toplevel"])
    if proc.returncode != 0:
        return None
    return proc.stdout.strip()


def _dirty_bundle_paths(root: str) -> list[str]:
    """Bundle paths whose working tree (including any staged changes)
    differs from HEAD. `git diff --name-only HEAD` covers both index and
    worktree deltas in one call."""
    proc = _run(["git", "-C", root, "diff", "--name-only", "HEAD", "--", *BUNDLE])
    if proc.returncode != 0:
        return []
    return [line.strip() for line in proc.stdout.splitlines() if line.strip()]


def _git_show(root: str, ref: str) -> str | None:
    proc = _run(["git", "-C", root, "show", ref])
    if proc.returncode != 0:
        return None
    return proc.stdout


def _backup_and_restore(root: str, paths: list[str]) -> tuple[str, bool, str]:
    """Snapshot the current (about-to-be-discarded) content of `paths` under
    /tmp, then restore each to its HEAD version.

    Returns (backup_dir, restored_ok, error_detail). Both halves are
    verified rather than assumed: a backup failure (e.g. a permission
    problem on a shared /tmp) aborts BEFORE any restore is attempted -- never
    discard working-tree content without a confirmed copy of it -- and a
    `git checkout` that fails (e.g. a concurrent process holding
    .git/index.lock) is reported as a failed restore instead of being
    silently treated as success.
    """
    stamp = time.strftime("%Y%m%dT%H%M%S", time.gmtime()) + f"-{int(time.time() * 1000) % 1000:03d}"
    backup_dir = os.path.join(BACKUP_ROOT, stamp)
    try:
        for rel in paths:
            src = os.path.join(root, rel)
            if not os.path.exists(src):
                continue
            dst = os.path.join(backup_dir, rel)
            os.makedirs(os.path.dirname(dst), exist_ok=True)
            shutil.copy2(src, dst)
    except OSError as exc:
        return backup_dir, False, f"backup failed, restore NOT attempted: {exc}"

    proc = _run(["git", "-C", root, "checkout", "HEAD", "--", *paths])
    if proc.returncode != 0:
        return backup_dir, False, f"git checkout failed (backup saved at {backup_dir}): {proc.stderr.strip()}"
    return backup_dir, True, ""


def check(root: str, threshold: float, *, check_only: bool) -> dict:
    """Returns a result dict; never raises for the ordinary "nothing to do"
    or "found and handled" paths. Raises only on a genuinely unreadable
    graph.json when it was flagged dirty (caller reports that as an error)."""
    dirty = set(_dirty_bundle_paths(root))
    result: dict = {
        "dirty": sorted(dirty),
        "destructive": False,
        "desync": False,
        "restored": False,
        "escaped": False,
        "backup_dir": None,
        "detail": "",
    }
    if not dirty:
        return result

    destructive = False
    node_detail = ""
    if GRAPH_PATH in dirty:
        head_raw = _git_show(root, f"HEAD:{GRAPH_PATH}")
        if head_raw is not None:
            # HEAD's own committed copy must parse -- if it doesn't, that is a
            # separate, pre-existing repo problem outside this guard's scope;
            # let it raise (caller reports it as an error, same as
            # check_graph_node_loss.py does for unparseable input).
            head_doc = json.loads(head_raw)
            before = _counts(head_doc, source="HEAD")
            working_path = os.path.join(root, GRAPH_PATH)
            try:
                with open(working_path, "r", encoding="utf-8") as fh:
                    working_doc = json.load(fh)
            except (OSError, json.JSONDecodeError) as exc:
                # A missing or corrupt working-tree graph.json is a WORSE
                # instance of the exact failure class this guards against
                # (total loss, not partial) -- not a reason to skip it.
                # Confirmed live 2026-08-21 the milder (partial-shrink) case
                # of this same file; this branch covers the total-loss case
                # nothing in that incident happened to exercise.
                destructive = True
                node_detail = f"graph.json missing/unreadable in working tree ({exc}) -- treating as total loss"
                result["node_detail"] = node_detail
            else:
                after = _counts(working_doc, source="working tree")
                pct = loss_pct(before["nodes"], after["nodes"])
                destructive = pct > threshold
                node_detail = " ".join(f"{k}={before[k]}->{after[k]}" for k in COUNTED_KEYS)
                result["node_loss_pct"] = round(pct, 4)
                result["node_detail"] = node_detail

    # Case B: graph.json itself is clean but a sibling (manifest/report) is
    # dirty. graph.json is the source of truth these are derived from, so if
    # it says nothing changed, a dirty sibling is a desync, not a choice.
    desync = GRAPH_PATH not in dirty and bool(dirty & {MANIFEST_PATH, REPORT_PATH})

    result["destructive"] = destructive
    result["desync"] = desync
    if not destructive and not desync:
        result["detail"] = f"dirty but within threshold ({threshold}%): {node_detail}"
        return result

    result["detail"] = (
        f"destructive node loss: {node_detail}" if destructive
        else f"sibling desync (graph.json clean, dirty siblings: {sorted(dirty)})"
    )

    if os.environ.get(ENV_ESCAPE) == "1":
        result["escaped"] = True
        return result

    if check_only:
        return result

    backup_dir, restored_ok, restore_error = _backup_and_restore(root, sorted(dirty))
    result["backup_dir"] = backup_dir
    result["restored"] = restored_ok
    if not restored_ok:
        result["detail"] += f" -- RESTORE FAILED: {restore_error}"
    return result


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check-only", action="store_true", help="report only, never restore")
    parser.add_argument("--threshold", type=float, default=None, help=f"max %% node loss (default {DEFAULT_MAX_LOSS_PCT})")
    parser.add_argument("--json", action="store_true", help="machine-readable output")
    args = parser.parse_args(argv)

    threshold = resolve_threshold(args.threshold)

    root = _repo_root()
    if root is None:
        print("check_graph_worktree_integrity: not a git repo", file=sys.stderr)
        return 2

    try:
        result = check(root, threshold, check_only=args.check_only)
    except (OSError, json.JSONDecodeError, ValueError) as exc:
        print(f"check_graph_worktree_integrity: cannot inspect graph: {exc}", file=sys.stderr)
        return 2

    if args.json:
        print(json.dumps(result, indent=2))
    elif not result["dirty"]:
        print("check_graph_worktree_integrity: OK (graphify-out/ bundle clean)")
    elif not result["destructive"] and not result["desync"]:
        print(f"check_graph_worktree_integrity: OK ({result['detail']})")
    elif result["escaped"]:
        print(f"check_graph_worktree_integrity: ALLOWED via {ENV_ESCAPE}=1 -- {result['detail']}")
    elif result["restored"]:
        print(f"check_graph_worktree_integrity: RESTORED -- {result['detail']}")
        print(f"  backup of discarded content: {result['backup_dir']}")
        print(f"  verify with: git -C {root} status --short graphify-out/")
    elif args.check_only:
        print(f"check_graph_worktree_integrity: FOUND (--check-only, not restored) -- {result['detail']}")
    else:
        print(f"check_graph_worktree_integrity: RESTORE FAILED -- {result['detail']}", file=sys.stderr)
        return 2

    return 0


if __name__ == "__main__":
    sys.exit(main())
