# ───────────────────────────────────────────────────────────────
# ✍️  Orion Meta Writer — Validates and Enriches Bus Messages
# ───────────────────────────────────────────────────────────────

services:
  meta-writer:
    build:
      context: ../..
      dockerfile: services/orion-meta-writer/Dockerfile
    container_name: ${PROJECT}-meta-writer
    image: ${PROJECT}-meta-writer:${SERVICE_VERSION:-latest}
    restart: unless-stopped
    networks:
      - app-net
    ports:
      - "${PORT:-8210}:${PORT:-8210}"
    environment:
      - PROJECT=${PROJECT}
      - SERVICE_NAME=${SERVICE_NAME}
      - SERVICE_VERSION=${SERVICE_VERSION}
      - PORT=${PORT}

      # Bus
      - ORION_BUS_URL=${ORION_BUS_URL}
      - ORION_BUS_ENABLED=${ORION_BUS_ENABLED}

      # Channels
      - CHANNEL_EVENTS_TAGGED=${CHANNEL_EVENTS_TAGGED}
      - CHANNEL_EVENTS_ENRICHED=${CHANNEL_EVENTS_ENRICHED}
      - CHANNEL_EVENTS_TRIAGE=${CHANNEL_EVENTS_TRIAGE}
      - CHANNEL_RDF_ENQUEUE=${CHANNEL_RDF_ENQUEUE}

      # Startup delay
      - STARTUP_DELAY=${STARTUP_DELAY}

    command: ["/bin/sh", "-c", "sleep ${STARTUP_DELAY:-5} && uvicorn app.main:app --host 0.0.0.0 --port ${PORT:-8210}"]

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT:-8210}/health"]
      start_period: 10s
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  app-net:
    name: ${NET:-app-net}
    external: true
