# ───────────────────────────────────────────────────────────────
# ✍️ Orion Meta Writer — Validates and Enriches Bus Messages
# ───────────────────────────────────────────────────────────────

services:
  meta-writer:
    build:
      context: ../..
      dockerfile: services/orion-meta-writer/Dockerfile
    container_name: ${PROJECT}-meta-writer
    restart: unless-stopped
    networks:
      - app-net
    ports:
      - "${PORT}:${PORT}"
    environment:
      - ORION_BUS_URL=${ORION_BUS_URL}
      - ORION_BUS_ENABLED=${ORION_BUS_ENABLED}
      - SERVICE_NAME=${SERVICE_NAME}
      - SERVICE_VERSION=${SERVICE_VERSION}
      - SUBSCRIBE_CHANNEL=${SUBSCRIBE_CHANNEL}
      - PUBLISH_CHANNEL=${PUBLISH_CHANNEL}
      - PORT=${PORT}


networks:
  app-net:
    name: ${NET}
    external: true

    #volumes:
    #  - /mnt/storage/collapse-mirrors:/mnt/storage/collapse-mirrors

