version: "3.9"

services:
  orion-vision:
    build:
      context: ../..
      dockerfile: services/orion-vision/Dockerfile
    container_name: orion-vision
    restart: unless-stopped
    environment:
      SOURCE: "${REOLINK_URL}"
      WIDTH: "${WIDTH}"
      HEIGHT: "${HEIGHT}"
      FPS: "${FPS}"

      DETECTORS: "${DETECTORS}"
      MOTION_MIN_AREA: "${MOTION_MIN_AREA}"
      DETECT_EVERY_N_FRAMES: "${DETECT_EVERY_N_FRAMES}"
      STREAM_ID: "${STREAM_ID}"
      ENABLE_UI: "${ENABLE_UI}"

      ENABLE_YOLO: "${ENABLE_YOLO}"
      YOLO_MODEL: "${YOLO_MODEL}"
      YOLO_CLASSES: "${YOLO_CLASSES}"
      YOLO_CONF: "${YOLO_CONF}"
      YOLO_DEVICE: "${YOLO_DEVICE}"

      FACE_CASCADE_PATH: "${FACE_CASCADE_PATH}"
      FACE_SCALE_FACTOR: "${FACE_SCALE_FACTOR}"
      FACE_MIN_NEIGHBORS: "${FACE_MIN_NEIGHBORS}"
      FACE_MIN_SIZE: "${FACE_MIN_SIZE}"

      ANNOTATE: "${ANNOTATE}"

      ENABLE_PRESENCE: "${ENABLE_PRESENCE}"
      PRESENCE_TIMEOUT: "${PRESENCE_TIMEOUT}"
      PRESENCE_LABEL: "${PRESENCE_LABEL}"

      JPEG_QUALITY: "${JPEG_QUALITY}"
      BRAIN_URL: "${BRAIN_URL}"
      ORION_BUS_URL: "${ORION_BUS_URL}"
      ORION_BUS_ENABLED: "${ORION_BUS_ENABLED}"
    ports:
      - "8000:8000"
    deploy: {}
    runtime: nvidia
    networks:
      - app-net

networks:
  app-net:
    external: true
