services:
  state-journaler:
    build:
      context: ../..
      dockerfile: services/orion-state-journaler/Dockerfile
    container_name: ${PROJECT}-state-journaler
    restart: unless-stopped
    networks:
      - app-net
    ports:
      - "${JOURNALER_PORT}:${JOURNALER_PORT}"
    environment:
      - SERVICE_NAME=${SERVICE_NAME}
      - SERVICE_VERSION=${SERVICE_VERSION}
      - NODE_NAME=${NODE_NAME}
      - PORT=${JOURNALER_PORT}

      - ORION_BUS_URL=${ORION_BUS_URL}
      - ORION_BUS_ENFORCE_CATALOG=${ORION_BUS_ENFORCE_CATALOG}
      - ORION_BUS_VELOCITY_TRACKING_ENABLED=${ORION_BUS_VELOCITY_TRACKING_ENABLED}
      - ORION_BUS_ENABLED=${ORION_BUS_ENABLED}

      - HEARTBEAT_INTERVAL_SEC=${HEARTBEAT_INTERVAL_SEC}

networks:
  app-net:
    name: ${NET}
    external: true
